### ISSUE TITLE
Circular Import Error when Loading

### ISSUE THREAD

**Issue by shahrozeabbas** [r-trimbour/atac-networks#2]
Hello,

I am testing out this package and was able to run it once, but now am experiencing this circular import error. 

Trying to figure out if it's something with my `conda` environment or the code. Would appreciate any advice, thanks!

`AttributeError: partially initialized module 'atacnet' has no attribute 'add_region_infos' (most likely due to a circular import)`

**Comment by r-trimbour** [comment]
Dear Shahrose,

Thanks a lot for your interest in atacnet :)

Did you install it through pip ?
If you used pip, it might be worth checking that it installed the last version, or enforce it through:
`pip install atacnet==0.1.6`

If you downloaded the github repo, this error also occurs when you launch python still located in the repo folder.
Let me know if this solves your error ! :)

Rémi

**Comment by r-trimbour** [comment]
Hello,

I'm closing this issue since it should be solved. 
Don't hesitate to open a new one if it's not ! :)
